channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3
  - pygame
  - pip:
    - numpy
    - sphinx
    - myst-parser
    - myst-nb
    - setuptools
    - jupyter
    - matplotlib
    - perfplot
    - build
