name: Build and test

on: [push]

jobs:
  build-linux:
    name: Build and test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spacetime
          environment-file: environment.yaml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Conda info
        run: conda info

      - name: Conda list
        run: conda list

          #- name: Lint with flake8
          #  shell: bash -el {0}
          #  run: |
          #    conda install flake8
          #    # stop the build if there are Python syntax errors or undefined names
          #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build spacetime
        shell: bash -el {0}
        run: |
          python setup.py install

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          pip install pytest
          pytest

      - name: Build docs
        shell: bash -el {0}
        run: |
          python setup.py build_sphinx
