name: Build and test

on: [push]

jobs:
  build-linux:
    name: Build and test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spacetime
          environment-file: environment.yaml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Conda info
        run: conda info

      - name: Conda list
        run: conda list

      - name: Build spacetime
        shell: bash -el {0}
        run: |
          python setup.py install

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          pip install pytest
          pytest

      - name: Build docs
        shell: bash -el {0}
        run: |
          python setup.py build_sphinx

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: build/sphinx/html/
          retention-days: 5

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/sphinx/html
